### ISSUE TITLE
StringArray option

### ISSUE THREAD

**Issue by sanex3339** [zakplus/obfuscator-loader#1]
Why `stringArray` option is disabled?

**Comment by zakplus** [comment]
Hi Timofey, when `stringArray` is true, webpack has a problem with the code generated by the obfuscator.
The code itself is correct but it contains "requires" with expressions as arguments (like this: `require(_0x430e('0x0'));`) and webpack does not like them:

`WARNING in ./src/index.js
23:14-37 Critical dependency: the request of a dependency is an expression
 @ ./src/index.js`

When this warning occurs, webpack generates a bundle which is missing the required module.

**Comment by sanex3339** [comment]
Better parse it and wrap in conditional conments

**Comment by zakplus** [comment]
I did not think about it, good advise! I'm releasing a new version without the stringArray limitation.  
Thank you Timofey!
