### ISSUE TITLE
Release version update

### ISSUE THREAD

**Issue by JerryChan31** [zakplus/obfuscator-loader#16]
Can someone publish v1.1.4 ? The package on npm is still v1.1.2.
https://github.com/javascript-obfuscator/obfuscator-loader/issues/11

**Comment by Rahulgarg30591** [comment]
Hello, @JerryChan31 may you kindly publish the same. I am awfully stuck as the target node version for me is 14.4 and it is not building. Please, Thank you.

**Comment by cameronbraid** [comment]
Can you also change the dependency on javascript-obfuscator to be a peer dependency so that it can be upgraded separately

**Comment by sanex3339** [comment]
Hi. I added the loader to `webpack-obfuscator` package. Check the readme. Loader based on the code of this package.

**Comment by sanex3339** [comment]
I marked this package as deprecated. Use loader https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage
