### ISSUE TITLE
SelfDefending works when building in production mode

### ISSUE THREAD

**Issue by KaminoRyo** [zakplus/obfuscator-loader#17]
obfuscator-loader : newest version (I'm pulling from Github instead of npm)

I set Obfuscator-loader to come last as instructed, but I was confused by the selfDefending feature working.😥
(Error : Maximum call stack size exceeded)
I don't use plugin.  program works when built in development mode.

webpack.config.js
```
      {
        test: /\.ts$/,
        use: [
          {
            loader: 'obfuscator-loader',
            options: (official "Low obfuscation, High performance" setting)
          },
          {
            loader: "babel-loader",
            options: {
              presets: [
                [
                  "@babel/preset-env",
                  {
                    "targets": { "ie": "11" }
                  }
                ]
              ]
            }
          },
          {
            loader: 'ts-loader',
            options: { transpileOnly: true }
          }
        ],
        exclude: /node_modules/
      }
```

**Comment by sanex3339** [comment]
Hi. Use loader bundled to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage

If this problem still will happen - create new issue there.
