### ISSUE TITLE
he number of constructor arguments in the derived class t must be 

### ISSUE THREAD

**Issue by k713927** [zakplus/obfuscator-loader#19]
hello,

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 2)
The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
    at PoolWorker.fromErrorObj (/Users/rf/programming/web/php/hd_plugin/node_modules/thread-loader/dist/WorkerPool.js:262:12)

env:
node -v = v14.6.0
npm -v   =6.14.7
vue-cli ,webpack

thank you

**Comment by k713927** [comment]
@zamotkin  @sanex3339

**Comment by sanex3339** [comment]
At first, please try the new loader that bundled in `webpack-obfuscator` package.
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage

It requires `javascript-obfuscator` as a peer dependency, so you have to describe it in your `dependencies` section.
Set last version `1.8.1`

**Comment by sanex3339** [comment]
Hi. Use loader bundled to the `webpack-obfuscator`
https://github.com/javascript-obfuscator/webpack-obfuscator#loader-usage
