### ISSUE TITLE
Move repository under javascript-obfuscator organisation

### ISSUE THREAD

**Issue by sanex3339** [zakplus/obfuscator-loader#2]
If you want, i can invite you to  `javascript-obfuscator` organisation and you will add this repo under this organisation.

https://github.com/javascript-obfuscator

**Comment by zakplus** [comment]
Hello Timofey, thank you for your proposal.
It would be great to add my repo to your organization.

**Comment by sanex3339** [comment]
I sent you an invitation.

**Comment by zakplus** [comment]
Ok, I transferred the repo.

**Comment by sanex3339** [comment]
Thank you. Added link on repo to the readme.md
